
project_id = "rlirtjxgwstjzraovntf"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[auth]
enabled = true
port = 54321

[db]
port = 54322

[storage]
enabled = true
port = 54323

[realtime]
enabled = true
port = 54324

[edge_functions]
[edge_functions.drugs-scraper]
verify_jwt = false
