// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rlirtjxgwstjzraovntf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsaXJ0anhnd3N0anpyYW92bnRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNTE0MTIsImV4cCI6MjA1OTYyNzQxMn0.GyUcMI0pyZ-1A6wJ5QZBG8EsFpiFW11Vy-zb2w_S2FA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);